# TMA4215 - Assignment 1, LU-factorisation with pivoting


**Deadline:** Wednesday September 2nd, 11:59PM.

**Requirements for approval:** You need to do two things: 1) Upload a Jupyter Notebook on Blackboard that contains the complete solution to the assigment and 2) Answer the Control question form of the assignment, you should make sure that at least some of the answers are correct.

**Supervision** of this assignment is digital. On Thursday August 27, 1600- the TA will be available for answering questions asked on Piazza and for one-to-one video conferencing on the platform Whereby.com.
At any other time you may ask questions on Piazza, but please be a little patient then, it may take some time before your question is answered.


This assignment is our way of compensating for not lecturing Gaussian elimination and LU-factorisation with pivoting. Many of you have seen this algorithm before. If your background on this method is weak, you can read up on chapters 3.2-3.5 in the text book.

In this assignment you are to implement and test a Python-program for doing LU-factorisation with pivoting.
In large simulations in real life it is often recommended to use as little memory as possible, and also avoid unnecessary operations that are time consuming. From this point of departure we would like you to make a code that takes the coefficient matrix $A$ as input and returns a representation of the matrices $P$, $L$, and $U$ which solve the equation

$$
     PA = LU
$$

where $P$ is a permutaton matrix, $L$ is a lower-triangular matrix with unit diagonal, and $U$ is an upper-triangular matrix. We *represent* the matrices in question as follows: The permutation matrix $P$ is $n\times n$, but is represented as a vector  $\mathtt{P}$ such that row number $k$ in $P$ is the canonical unit vector $e_{\mathtt{P}_k}$. Let us illustrate this by an example

$$
\mathtt{P}=
\left[
\begin{array}{r} 3 \\ 1 \\ 2 \end{array}
\right]\quad\Rightarrow\quad
P=\left[
\begin{array}{ccc}
0 & 0 & 1 \\ 1 & 0 & 0 \\ 0 & 1 & 0
\end{array}
\right]
$$

We stipulate that a Python function takes a two-dimensional numpy-array $\mathtt{A}$ as input, and returns
an *over-written* $\mathtt{A}$ which contains $L$ and $U$ in the following sense upon return:

$$
\begin{array}{ll}
\mathtt{A}[\mathtt{P}[i],j] = L_{ij} & \text{for}\ i<j \\
\mathtt{A}[\mathtt{P}[i],j] = U_{ij} & \text{for}\ i\geq j
\end{array}
$$

That $L$ has 1 on the diagonal is always the case, so the diagonal of $L$ needs not be stored. The remaining elements of $L$ and $U$ are zero and need not be stored either. The algorithm can be formulated as follows (compare to text book):


- Input: $A$ of size $n\times n$
- Initialisation
    * Let $P_i = i,\ i=0,\ldots,n-1$ be a vector (array) with $n$ components
- for $k$ **in** range(n-1):
    1. Find index $P_\ell$ such that $|\mathtt{A}_{P_\ell,k}|=\max_{k\leq i \leq n-1} |\mathtt{A}_{P_i,k}|$, i.e. scan column $k$ from the diagonal and down for the largest element in absolute value. 
    2. Swap $P_k$ by $P_\ell$.
    3. Find multipliers $A_{P_i,k}\leftarrow \frac{A_{P_i,k}}{A_{P_k,k}},\ i=k+1,\ldots,n-1$.
    4. Perform elimination, i.e. $A_{P_i,j}\leftarrow A_{P_i,j}-A_{P_i,k}\cdot A_{P_k,j},\ i,j=k+1,\ldots,n-1$
- Output: A,P

**Comment:** In practice there are of course off the shelf implementations both in Python libraries and other places for solving linear systems in an optimal way with respect to accuracy and efficiency. It also happens often that many elements of the coefficient matrix are zero and that can be exploited in various different ways. The solver you make is rather general. Irrespective of whether the code you implement is standard software, it is a useful experience to have written such a program yourself at least once, so that you understand how it works, the kind of errors that may occur etc, and you will gain understanding for instance in error analysis.



**Problem 1** Write a function for LU-factorisation with row-wise pivoting as indicated above.
A template could be


    def mylu(A):
   
    
and it should return the pivot vector (permutation vector) $\mathtt{P}$, and and over-written  version of $A$. You can also choose to copy $A$ into some other matrix $\mathtt{LU}$ from the beginning using e.g. 

    LU = A.copy()

and write into and return this matrix in order to save the input matrix $A$ 

Use the algorithm described above. See hints about indexing and useful numpy-functions that can be used below.

**Problem 2** Combine your function (mylu) with the functions for forward and backward substitution given below for computing solutions to linear systems $Ax=b$. Test it out by using $A$ and $b$ from the function getAb() below.

**Control question 1:** Give the permutation vector $\mathtt{P}$ from this numerical test (multiple choice)

**Control question 2:** Give the first component of the intermediate result $c$ (where $Lc=Pb$) (multiple choice)

**Control question 3:** Give the last component in the final answer $x$ (where $Ax=b$) with the given example.

**Approval**
A Jupyter notebook file with code that solves Problems 1 and 2 isto be uploaded in Blackboard and you need to answer the control questions.



## Some Python and numpy stuff
In LU-factorisation with partial (row-wise) pivoting, one needs to make use of indirect addressin of arrays via a permutation vector $\mathtt{P}$. Below you find some examples of how things can be done.

In [363]:
import numpy as np

A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
P=np.array([2,3,0,1])
m,n = A.shape
print('A=\n',A)
print('\n\nPermutation vector P=',P)
k=1

print('\n\nThe rows of A sorted according to P\n, written: A[P,]\n\n', A[P,])

print('\n\nColumn k(=',k,') sorted according to P, written: A[P,k]\n',A[P,k])
print('\n\n Fetch the last part of column k in A sorted according P: A[P[k:],k]\n', A[P[k:],k])



print('\n\n***\n\n')

print('The numpy-function np.outer can be handy in doing item 4 above\n')
print('Example:\n Let x,y be\n') 
x=np.array([1,2,3]) 
y=np.array([1,0,-1])
print('x=',x,'\ny=',y)
print('\nThen np.outer(x,y)=\n',np.outer(x,y))

k=2
print('\n\nThe numpy function argmax can be useful in seeking the pivot-element (row to be swapped)\n')
pivot = np.argmax(abs(A[P[k:], k]))+k
print('Write for instance: pivot = np.argmax(abs(A[P[k:], k])+k\n yielding pivot=',pivot, 'når k=',k)

AA=np.random.rand(5,5)
print('\n\n AA=\n',AA)



A=
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Permutation vector P= [2 3 0 1]


The rows of A sorted according to P
, written: A[P,]

 [[ 9 10 11 12]
 [13 14 15 16]
 [ 1  2  3  4]
 [ 5  6  7  8]]


Column k(= 1 ) sorted according to P, written: A[P,k]
 [10 14  2  6]


 Fetch the last part of column k in A sorted according P: A[P[k:],k]
 [14  2  6]


***


The numpy-function np.outer can be handy in doing item 4 above

Example:
 Let x,y be

x= [1 2 3] 
y= [ 1  0 -1]

Then np.outer(x,y)=
 [[ 1  0 -1]
 [ 2  0 -2]
 [ 3  0 -3]]


The numpy function argmax can be useful in seeking the pivot-element (row to be swapped)

Write for instance: pivot = np.argmax(abs(A[P[k:], k])+k
 yielding pivot= 3 når k= 2


 AA=
 [[0.73140305 0.73240262 0.58294121 0.9281923  0.46637445]
 [0.92734481 0.16647233 0.0313021  0.0626339  0.57604892]
 [0.21541321 0.37262598 0.52794564 0.03822034 0.64634808]
 [0.29184818 0.00928003 0.99567978 0.11567624 0.57862099]
 [0.8907555  0.6595281  0.6720361

## Codes for forward and bacwards substitution
To make life easier for you, we give you two functions that can be called in order to solve Ax=b after one has LU-factorised with pivoting. It presumed that a matrix LU has been computed, and a permutation vector P.

In [364]:
def forward_subs(LU,P,b):
    ''' Forward substitution algorithm
    Input:
        LU contains both L and U, even if only L is needed here 
        P Integer permutation vector
        b Vector with right hand side in the problem to be solved
    Output:
        c The solution to the linear lower triangular system Lc=b 
    '''
    n, m = LU.shape
    Pb = b[P]
    c = np.zeros(n)
    c[0] = Pb[0]
    for k in range(1,n):
        c[k] = Pb[k] - LU[P[k],0:k] @ c[0:k]
        
    return c

def backward_subs(LU,P,c):
    ''' Backward substitution algorithm
    Input:
        LU contains both L and U, even though just U is needed here
        P Integer permutation vector
        c Vector containing right hand side, i.e. the function solves Ux=c
    Output:
        x Solution to the linear upper triangular system Ux = c
    '''
    n,m = LU.shape
    x = np.zeros(n)
    x[n-1] = c[n-1]/LU[P[n-1],n-1]
    for k in range(n-1,0,-1):
        x[k-1] = (c[k-1]-LU[P[k-1],k:] @ x[k:])/LU[P[k-1],k-1]
        
    return x

In [365]:
def getAb():
    A=np.array([[0.3050, 0.5399, 0.9831, 0.4039, 0.1962],
                [0.2563, -0.1986, 0.7903, 0.6807, 0.5544],
                [0.7746, 0.6253, -0.1458, 0.1704,  0.5167],
                [0.4406, 0.9256, 0.4361, -0.2254, 0.7784],
                [0.4568, 0.2108, 0.6006, 0.3677, -0.8922]])
    b=np.array([0.9876,-1.231,0.0987,-0.5544,0.7712])
    return A,b
    


## Problem 1
Write a function for LU-factorisation with row-wise pivoting as indicated above.

- Input: $A$ of size $n\times n$
- Initialisation
    * Let $P_i = i,\ i=0,\ldots,n-1$ be a vector (array) with $n$ components
- for $k$ **in** range(n-1):
    1. Find index $P_\ell$ such that $|\mathtt{A}_{P_\ell,k}|=\max_{k\leq i \leq n-1} |\mathtt{A}_{P_i,k}|$, i.e. scan column $k$ from the diagonal and down for the largest element in absolute value. 
    2. Swap $P_k$ by $P_\ell$.
    3. Find multipliers $A_{P_i,k}\leftarrow \frac{A_{P_i,k}}{A_{P_k,k}},\ i=k+1,\ldots,n-1$.
    4. Perform elimination, i.e. $A_{P_i,j}\leftarrow A_{P_i,j}-A_{P_i,k}\cdot A_{P_k,j},\ i,j=k+1,\ldots,n-1$
- Output: A,P

In [366]:
def lu(A):
    n, m = A.shape
    assert n == m, "A must be square!"
    p = np.arange(n)
    for k in range(n - 1):
        l = np.argmax(np.abs(A[p[k:],k])) + k
        p[[k, l]] = p[[l, k]]
        A[p[k+1:], k] /= A[p[k], k]
        A[p[k+1:], k+1:] -= np.outer(A[p[k+1:], k], A[p[k], k+1:])
    return A, p

$$
\begin{array}{ll}
\mathtt{A}[\mathtt{P}[i],j] = L_{ij} & \text{for}\ i<j \\
\mathtt{A}[\mathtt{P}[i],j] = U_{ij} & \text{for}\ i\geq j
\end{array}
$$

In [367]:
def AP2LU(A, p):
    n = A.shape[0]
    L = np.eye(n)
    U = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            if i < j:
                L[i,j] = A[p[i], j]
            else:
                U[i,j] = A[p[i], j]
    return L, U

In [368]:
A, b = getAb()# print("A:\n", A)

print("A:\n", A)
print("b:\n", b)
x_true = np.linalg.solve(A, b)
print("True solution:\n", x_true)
A, p = lu(A)
c = forward_subs(A, p, b)
print("c:\n", c)
x = backward_subs(A, p, c)
print("Tried solution:\n", x)
error = np.linalg.norm(x_true - x)
print(f"Error from correct solution: {error}")
print("SUCCESS!" if error < 1e-10 else "FAILURE...")

A:
 [[ 0.305   0.5399  0.9831  0.4039  0.1962]
 [ 0.2563 -0.1986  0.7903  0.6807  0.5544]
 [ 0.7746  0.6253 -0.1458  0.1704  0.5167]
 [ 0.4406  0.9256  0.4361 -0.2254  0.7784]
 [ 0.4568  0.2108  0.6006  0.3677 -0.8922]]
b:
 [ 0.9876 -1.231   0.0987 -0.5544  0.7712]
True solution:
 [-4.74452344  5.22095642 -2.29120587  5.31222591 -1.41303909]
c:
 [ 0.0987     -0.61054152 -1.69805726  2.35015812  2.59163195]
Tried solution:
 [-4.74452344  5.22095642 -2.29120587  5.31222591 -1.41303909]
Error from correct solution: 2.220446049250313e-16
SUCCESS!


## Problem 2
Combine your function (mylu) with the functions for forward and backward substitution given below for computing solutions to linear systems $Ax=b$. Test it out by using $A$ and $b$ from the function getAb() below.

In [369]:
def solve(A, b):
    A, p = lu(A)
    return backward_subs(A, p, forward_subs(A, p, b)), p

In [370]:
A, b = getAb()
n = len(A)
A_copy = A.copy()
x_numpy = np.linalg.solve(A, b)
x_lu, p = solve(A, b)
print("Numpy:\n", x_numpy)
print("LU:\n", x_lu)
print("p:\n", p)
L, U = AP2LU(A, p)
print("L:\n", L)
print("U:\n", U)
import scipy
LU_np, p = scipy.linalg.lu_factor(A_copy)
print("L_np:\n", np.triu(LU_np, k=1) + np.eye(n))
print("U_np:\n", np.tril(LU_np))

Numpy:
 [-4.74452344  5.22095642 -2.29120587  5.31222591 -1.41303909]
LU:
 [-4.74452344  5.22095642 -2.29120587  5.31222591 -1.41303909]
p:
 [2 3 1 0 4]
L:
 [[ 1.          0.6253     -0.1458      0.1704      0.5167    ]
 [ 0.          1.          0.51903246 -0.32232517  0.48449602]
 [ 0.          0.          1.          0.3949841   0.72815225]
 [ 0.          0.          0.          1.         -0.72295451]
 [ 0.          0.          0.          0.          1.        ]]
U:
 [[ 0.7746      0.          0.          0.          0.        ]
 [ 0.56880971  0.56992329  0.          0.          0.        ]
 [ 0.33088045 -0.71149847  1.20783317  0.          0.        ]
 [ 0.39375161  0.5153099   0.64002748  0.2501014   0.        ]
 [ 0.58972373 -0.27715001  0.68753831 -0.37460027 -1.83408369]]
L_np:
 [[ 1.          0.6253     -0.1458      0.1704      0.5167    ]
 [ 0.          1.          0.51903246 -0.32232517  0.48449602]
 [ 0.          0.          1.          0.3949841   0.72815225]
 [ 0.      